modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-BashFireMakeRock/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sbm-bash-fire-make-rock"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="bashfiremakerock" #mandatory
version="1.0.0" #mandatory
displayName="[SBM] Bash Fire Make Rock" #mandatory
description='''Joke mod/concept to create fire when clicking blocks.
The name itself is intentially messed up. The orginal concept was a caveman story of creating rocks when bashing fire.
AS when you bash fire in MC the fire vanishes leaving only rock under it.''' #mandatory

[[dependencies.bashfiremakerock]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bashfiremakerock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"